image: alpine:latest

pages:
  stage: deploy
  before_script:
  - apt-get install -y npm
  script:
  - npm install
  - npm run dev
  artifacts:
    paths:
    - bountium-dao-storefronts/public
  only:
  - master